# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: true
    ignore_title_keywords: []
    labels: []
    # Explicitly allow CodeRabbit to review PRs from this author by keeping them out of ignore_usernames.
    # allowed_usernames:
    #   - google-labs-jules
    ignore_usernames: []
